### ISSUE TITLE
add tekhex unpacker

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/fact_extractor#21]
[Tektronix extended HEX](https://en.wikipedia.org/wiki/Tektronix_extended_HEX) is a binary hex format and was found in samples (e.g. `db52848359d4152f2f60b155e1e32dd7d38f75079da897ba1130604b5adcedba_383837`).
Currently, we have no unpacker for the format, but it could be realized easily using either `objcopy` or the [SRecord tool](http://srecord.sourceforge.net/).

**Comment by 0xricksanchez** [comment]
First versions for a tek and xtek unpacker are ready.
