### ISSUE TITLE
Add extract-vmlinux unpacker

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/fact_extractor#31]
File already knows the signature for bzImage or other vmlinux files, only a mime is missing.
Also there is an official [script](https://raw.githubusercontent.com/torvalds/linux/master/scripts/extract-vmlinux) to do that (duh).

Adding this would make file trees of linux based firmware look a lot nicer.

**Comment by Caesurus** [comment]
Inadvertently addressed in https://github.com/fkie-cad/fact_extractor/pull/69
