### ISSUE TITLE
optional header for srec unpacker

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/fact_extractor#34]
the header of srec files seems to be optional so this should be considered during unpacking
i.e. 40ba21d58b0e5d51517b9462945a4a65341c63b0ff45f468de9fe9b8d96155bc_799985

**Comment by 0xricksanchez** [comment]
The srec unpacker decodes a fed srec block line by line. As long as each line is in a valid srec format the unpacker will successfully decode it. Currently, no formal check of the fed block is done (e.g. checking for a header and termination entry). 

Hence a missing header entry does not affect the unpacker implementation. 
The problem occurs in the mime regex in the https://github.com/fkie-cad/fact_helper_file
