### ISSUE TITLE
serious problem

### ISSUE THREAD

**Issue by ajisky** [fkie-cad/fact_extractor#38]
sorry, i not use --privileged launch docker

**Comment by dorpvom** [comment]
Ah, okay. So issue closed?

**Comment by dorpvom** [comment]
Btw. Which FSs are mounted correctly, depends on your Host OS. I've encountered multiple occasions where e.g. different Ubuntu LTS versions would behave differently since they have differing fs support.

**Comment by weidenba** [comment]
Issue seems to be solved.
