### ISSUE TITLE
Add support for recursive extraction

### ISSUE THREAD

**Issue by njv299** [fkie-cad/fact_extractor#4]
This docker container provides a useful capability, but it is very limited in that it only extracts a single file and does not attempt to recursively extract all additional files. It would be much more useful if a '--recursive' flag was added that enabled extraction to attempt to unpack an entire nested firmware using the same overall methodology that FACT_core uses.

**Comment by weidenba** [comment]
I see your point. However, our intention of this tool is a simple and small one layer extraction. This tool is going to replace FACT_core unpacking functionality in the near future. For technical reasons the recursion must stay a part of FACT_core.
Nevertheless, it sould be easy to write a little python script, that adds the recursion functionality.

**Comment by njv299** [comment]
Thanks for your feedback, that's really interesting to hear that this is envisioned as a replacement for FACT_core's unpacking. Does that mean that the analyzers will also be moved into a Docker container?

**Comment by weidenba** [comment]
We already dockerd some of the analysis plug-ins for different reasons. We are going put more of them into container if they need a lot of none-python dependencies. However, this is not a project for the near future.
