### ISSUE TITLE
HP PJL extractor metadata causes exception when writing report file

### ISSUE THREAD

**Issue by njv299** [fkie-cad/fact_extractor#6]
HP PJL extraction writes the raw PJL commands to the output. These raw commands can contain non-printable characters, and is stored as a `bytes` object. The fact_extractor unpacker writes the output of each extractor as serialized JSON to the meta.json file, and therefore when HP-PJL extraction results are written an exception of 'TypeError: Object of type 'bytes' is not JSON serializable' occurs.

To reproduce this, try to unpack any file which goes through the HP PJL extractor via the fact_extractor container.

**Comment by dorpvom** [comment]
This issue will be solved more generally in branch [safer-report-generation](https://github.com/fkie-cad/fact_extractor/tree/)

**Comment by dorpvom** [comment]
cf. #7
