### ISSUE TITLE
Introduce option to preserve empty files and symlinks

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/fact_extractor#84]
The FACT extraction process ignores empty files and duplicates such that after extraction, all such files are dropped before they are moved to our destination folder. This can lead to multiple unwanted side effects. To preserve a full extraction **fact_extractor** should introduce parameters that makes keeping all files optional through docker wrapper and direct execution.

https://github.com/fkie-cad/fact_extractor/blob/7d4a14d59bb8a7c6ba27ccf5623c157e5fd90c1e/fact_extractor/unpacker/unpack.py#L82

This should be the critical code switch that has to be parametrized.

**Comment by jstucke** [comment]
Resolved by #86
